Repository jyj2187/project-rhinitis-back, pull requests merged in 2023-09, with the labels that each got.

#21 Feat/post
  .gitignore
  src/main/java/com/rhinitis/projectrhinitis/dto/MultiResponseDto.java
  src/main/java/com/rhinitis/projectrhinitis/dto/PageInfo.java
  src/main/java/com/rhinitis/projectrhinitis/post/controller/PostController.java
  src/main/java/com/rhinitis/projectrhinitis/post/dto/PostDto.java
  src/main/java/com/rhinitis/projectrhinitis/post/service/PostService.java
  src/main/java/com/rhinitis/projectrhinitis/post/service/PostServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/rhinitis/projectrhinitis/post/service/PostServiceTest.java
Labels: Done

#24 feat:edit editpost
  src/main/java/com/rhinitis/projectrhinitis/post/controller/PostController.java
Labels: Done

#25 Feat/post to Dev
  src/main/java/com/rhinitis/projectrhinitis/post/controller/PostController.java
Labels: 배포, Done

#26 RDBMS 및 AWS RDS 설정 적용
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 수정, 배포, Done
